# Generated by Django 5.2.1 on 2025-06-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl', '0002_remove_userprofile_skill_userprofile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_links',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
